# Generated by Django 5.2.15 on 2026-06-08 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True, verbose_name='品牌名稱')),
                ('country', models.CharField(max_length=50, verbose_name='來源國家')),
                ('founded_year', models.IntegerField(blank=True, null=True, verbose_name='成立年份')),
            ],
            options={
                'verbose_name': '手機品牌',
                'verbose_name_plural': '手機品牌',
            },
        ),
        migrations.CreateModel(
            name='MobileShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, verbose_name='店舖名稱')),
                ('district', models.CharField(max_length=50, verbose_name='地區')),
                ('address', models.TextField(verbose_name='地址')),
                ('phone', models.CharField(max_length=20, verbose_name='聯絡電話')),
                ('is_carrier', models.BooleanField(default=False, verbose_name='是否為電訊網絡供應商')),
                ('carrier_name', models.CharField(blank=True, max_length=100, verbose_name='供應商名稱')),
            ],
            options={
                'verbose_name': '手機店舖',
                'verbose_name_plural': '手機店舖',
            },
        ),
        migrations.CreateModel(
            name='MobileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='型號名稱')),
                ('price_hkd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='港幣零售價')),
                ('release_date', models.DateField(verbose_name='發佈日期')),
                ('storage', models.CharField(max_length=20, verbose_name='儲存容量')),
                ('ram', models.CharField(max_length=10, verbose_name='記憶體')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='mobile_shop.mobilebrand')),
            ],
            options={
                'verbose_name': '手機型號',
                'verbose_name_plural': '手機型號',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='庫存數量')),
                ('mobile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='mobile_shop.mobilemodel')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='mobile_shop.mobileshop')),
            ],
            options={
                'verbose_name': '庫存記錄',
                'verbose_name_plural': '庫存記錄',
            },
        ),
    ]
